### ISSUE TITLE
multiply and approxequal have different widths

### ISSUE THREAD

**Issue by tphinney** [googlefonts/science-gothic#324] opened 2024-01-04 04:22 UTC
Check math signs have the same width.
Check ID: com.google.fonts/check/math_signs_width
It is a common practice to have math signs sharing the same width (preferably the same width as tabular figures accross the entire font family).

This probably comes from the will to avoid additional tabular math signs knowing that their design can easily share the same width.

⚠️ ScienceGothic[YOPQ,slnt,wdth,wght].ttf
⚠️ WARN
The most common width is 1438 among a set of 11 math glyphs. The following math glyphs have a different width, though:

Width = 1274: multiply

Width = 1218: uni223C, approxequal [code: width-outliers]

**Comment by kateliev** [comment] 2024-06-10 08:55
@tphinney we could kind of "tabulate" some of the math symbols if required:
Please see the attached table that i've created for our current math symbols.
[Math_Widths.xlsx](https://github.com/user-attachments/files/15759411/Math_Widths.xlsx)

**Comment by kateliev** [comment] 2024-06-14 09:00
Duplicate of newer one #337.

**Closed by kateliev** 2024-06-14 09:00 UTC
Labels: bug, FontBakery, next build
