### ISSUE TITLE
Clone :Lt, :LtCnd :LtExp :LtS :LtCndS :LtExpS to their respective contrast masters

### ISSUE THREAD

**Issue by servantb** [googlefonts/science-gothic#207] opened 2019-11-15 17:23 UTC
We've been doing this as we go along, by and large, but I'm still seeing inconsistencies in metrics between the :LtEtc and :LTCtrEtc masters at least, and am concerned there may be more differences than just metrics at worst.

**Comment by tphinney** [comment] 2019-11-15 17:59
We could do this essentially globally, as a verification step.

I suggest I do this on the weekend, when nobody else is working. Perhaps my last major thing, as a separate check-in—so if somehow it messes things up, we can revert to the previous fairly easily....

**Comment by kateliev** [comment] 2019-11-25 13:53
I strongly advise you not to do this globally! _This should have been done by designers while working daily on glyphs._ Might lead to major complications if ran globally especially in composite glyphs. If you decide to do it no matter my warning - please do it in small batches ans keep your eyes open for the following problems:

- glyphs with named elements will lose those names - glyphs depending on those will automatically re-reference as new base shapes - no actual harm done except for future editing if needed, but will generate additonal elements as garbage in Font Gallery
- glyphs with composites will have their composites referencing to the source layers not to their respective layer level this is mainly due to the new FL paradigm that allows layer cross-links. 

Cyrillic is perfect match! Also has overlaps removed in all glyphs! If possible please avoid it!

Suggestion: as I keep fining glyphs with overlaps not-removed, my advice is respective designers to go trough these, finish the job, then copy layers.

**Comment by tphinney** [comment] 2019-11-26 02:30
I understand your concerns. I would do it on specifically selected glyphs. A large number of them, but not all. Primarily the core alphabetics, numerals, etc.

Personally, I have never used named elements on any project. So that’s not a problem. And I know which glyphs might conceivably involve composites. So I can take care on that.

**Comment by kateliev** [comment] 2024-07-26 12:11
The issue is too dated to be still relevant. Closing.

**Closed by kateliev** 2024-07-26 12:11 UTC
Labels: bug, font global
